# Use an official base image
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/your-app.jar /app/

# Expose the port
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "your-app.jar"]
